// reactjs-todo/src/app/components/TaskList/TaskList.js
import React from 'react';
import { Task } from '../Task/Task';
import './TaskList.scss';

export const TaskList = (props) => {
  props = props.data;

  let createTaskItem = function(task, index) {
    return (
      <Task
        key={task.id}
        data={props}
        index={index}
      />
    );
  };

  let updateTaskList = function(newTasksArray) {
    props.data.setTasksArray(newTasksArray);
  };

  return (
    <div className="todo-list">
      <div className="overlay"></div>

      <div className="filter-btns">
        <button className={"all-filter " + (props.data.currentFilter === 'all' ? 'active' : '')}
                onClick={props.setCurrentFilter.bind(null, 'all')}>
          All
        </button>
        <button className={"progress-filter " + (props.data.currentFilter === 'progress' ? 'active' : '')}
                onClick={props.setCurrentFilter.bind(null, 'progress')}>
          Progress
        </button>
        <button className={"done-filter " + (props.data.currentFilter === 'done' ? 'active' : '')}
                onClick={props.setCurrentFilter.bind(null, 'done')}>
          Done
        </button>
      </div>

      <ul className={props.data.currentFilter}>
        {props.data.tasksArray.map(createTaskItem)}
      </ul>
    </div>
  );
};

// angular-todo/angular2-todo-app/src/app/todo/task-list/task-list.component.ts
import { Component   } from '@angular/core';

import { DataService } from '../core/data.service';

@Component({
  selector: 'app-task-list',
  templateUrl: './task-list.component.html',
  styleUrls: ['./task-list.component.css']
})

export class TaskListComponent {
  constructor(public _dataService: DataService) { }
}

<div class="todo-list">
  <div class="overlay" [class.active]="_dataService.openEditBlock"></div>

  <div class="filter-btns">
    <button class="all-filter"
            [class.active]="_dataService.currentFilter === 'all'"
            (click)="_dataService.currentFilter = 'all'">
      All
    </button>
    <button class="progress-filter"
            [class.active]="_dataService.currentFilter === 'progress'"
            (click)="_dataService.currentFilter = 'progress'">
      In progress
    </button>
    <button class="done-filter"
            [class.active]="_dataService.currentFilter === 'done '"
            (click)="_dataService.currentFilter = 'done'">
      Done
    </button>
  </div>

  <ul [ngClass]="_dataService.currentFilter">
    <app-task *ngFor="let task of _dataService.tasksArray; let i = index"
              [index]="i">
    </app-task>
  </ul>
</div>
