// reactjs-todo/src/app/components/Task/Task.js
import React from 'react';

export const Task = (props) => {
  const currentIndex = props.index;
  props = props.data;

  let checkFilter = function (task) {
    if (task.done) {
      return (props.data.currentFilter === 'all' || props.data.currentFilter === 'done');
    } else {
      return (props.data.currentFilter === 'all' || props.data.currentFilter === 'progress');
    }
  };

  let onDoneClick = function() {
    const tempTasksArray = props.data.tasksArray;
    tempTasksArray[currentIndex].done = !tempTasksArray[currentIndex].done;

    console.log(props);
    props.setTasksArray(tempTasksArray);

    if(props.data.isStorageAvailable) {
      localStorage.setItem(props.data.storageName, JSON.stringify(props.data.tasksArray));
    }
  };

  let onRemoveTask = function() {
    const tempTasksArray = props.data.tasksArray;
    tempTasksArray.splice(currentIndex, 1);

    props.setTasksArray(tempTasksArray);

    if(props.data.isStorageAvailable) {
      localStorage.setItem(props.data.storageName, JSON.stringify(props.data.tasksArray));
    }
  };

  let handleEditClick = function() {
    props.data.openEditBlock = !props.data.openEditBlock;
    props.data.currentTask = currentIndex;
  };

  const itemClassName = "task clearfix "
      + (checkFilter(props.data.tasksArray[currentIndex]) ? 'active' : '')
      + ((!!props.data.tasksArray[currentIndex].done) ? ' done' : '');

  const doneIconClassName = "material-icons task-done-icon "
      + ((!!props.data.tasksArray[currentIndex].done) ? 'active' : '');

  return (
    <li className={itemClassName}>
      <i className={doneIconClassName}
         onClick={onDoneClick}>
        done
      </i>
      <p>{props.data.tasksArray[currentIndex].name}</p>
      <i className="material-icons task-close-icon" onClick={onRemoveTask}>
        close
      </i>
      <button className="task-edit-btn"
              disabled={props.data.tasksArray[currentIndex].done}
              onClick={handleEditClick}>
        Edit
      </button>
    </li>
  );
};

// angular-todo/angular2-todo-app/src/app/todo/task-list/task/task.component.ts
import { Component, Input  } from '@angular/core';

import { StorageService    } from '../../shared/storage.service';
import { DataService       } from '../../core/data.service';

@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.css']
})

export class TaskComponent {
  @Input()
  index: number;

  constructor(private _storageService: StorageService,
              public _dataService: DataService) { }

  onEditClick() {
    this._dataService.currentTask = this.index;
    this._dataService.openEditBlock = !this._dataService.openEditBlock;
  }

  onDoneClick() {
    this._dataService.tasksArray[this.index].done = !this._dataService.tasksArray[this.index].done;

    if (this._dataService.isStorageAvailable) {
      this._storageService.saveData(this._dataService.storageName, this._dataService.tasksArray);
    }
  }

  onRemoveTask() {
    this._dataService.tasksArray.splice(this.index, 1);

    if (this._dataService.isStorageAvailable) {
      this._storageService.saveData(this._dataService.storageName, this._dataService.tasksArray);
    }
  }

  checkFilter() {
    if (this._dataService.tasksArray[this.index].done) {
      return (this._dataService.currentFilter === 'all' || this._dataService.currentFilter === 'done');
    } else {
      return (this._dataService.currentFilter === 'all' || this._dataService.currentFilter === 'progress');
    }
  }

  checkTaskForDone() {
    return !!this._dataService.tasksArray[this.index].done;
  }
}

<li class="task clearfix"
    [class.done]="checkTaskForDone()"
    [class.active]="checkFilter()">
  <i class="material-icons task-done-icon"
     [class.active]="_dataService.tasksArray[index].done"
     (click)="onDoneClick()">
    done
  </i>
  <p>{{_dataService.tasksArray[index].name}}</p>
  <i class="material-icons task-close-icon" (click)="onRemoveTask()">close</i>
  <button class="task-edit-btn"
          [disabled]="_dataService.tasksArray[index].done"
          (click)="onEditClick()">
    Edit
  </button>
</li>
