// task4/angular2-todo-app/src/app/todo/todo.component.ts
import { Component, OnInit                  } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})

export class TodoComponent implements OnInit {
  todoForm: FormGroup;
  editForm: FormGroup;
  tasksArray = [];
  isStorageAvailable = false;
  openEditBlock: false;
  currentTask: number;
  currentFilter = 'all';

  constructor(private _formBuilder: FormBuilder) {
    this.todoForm = this._formBuilder.group({
      'taskName': [null, Validators.required]
    });

    this.editForm = this._formBuilder.group({
      'newTaskName': [null, Validators.required]
    });
  }

  ngOnInit() {
    this.getListFromStorage();
  }

  getListFromStorage() {
    if (typeof localStorage !== 'undefined') {
      this.tasksArray = JSON.parse(localStorage.getItem('tasksArray')) || [];
      this.isStorageAvailable = true;
    } else {
      console.log('Local storage is not available.');
      this.isStorageAvailable = false;
    }
  }

  saveListToStorage() {
    localStorage.setItem('tasksArray', JSON.stringify(this.tasksArray));
  }

  addNewTask(form) {
    this.tasksArray.unshift({
      name: form.taskName,
      done: false
    });

    if (this.isStorageAvailable) {
      this.saveListToStorage();
    }

    this.todoForm.reset();
  }

  onDoneClick(index: number) {
    this.tasksArray[index].done = !this.tasksArray[index].done;

    if (this.isStorageAvailable) {
      this.saveListToStorage();
    }
  }

  onRemoveTask(index: number) {
    this.tasksArray.splice(index, 1);

    if (this.isStorageAvailable) {
      this.saveListToStorage();
    }
  }

  onSaveClick(event) {
    event.preventDefault();

    this.tasksArray[this.currentTask].name = this.editForm.controls['newTaskName'].value;
    this.openEditBlock = false;

    if (this.isStorageAvailable) {
      this.saveListToStorage();
    }
  }

  checkFilter(task) {
    if (task.done) {
      if (this.currentFilter === 'all' || this.currentFilter === 'done') {
        return true;
      } else {
        return false;
      }
    } else {
      if (this.currentFilter === 'all' || this.currentFilter === 'progress') {
        return true;
      } else {
        return false;
      }
    }
  }

  checkTaskForDone(task) {
    return !!task.done;
  }
}

<div class="todo">
  <form [formGroup]="todoForm" (ngSubmit)="addNewTask(todoForm.value)">
    <input class="task-input"
           type="text"
           placeholder="Enter task name..."
           [formControl]="todoForm.controls['taskName']" />
    <button type="submit"
            class="add-task-btn"
            [disabled]="!todoForm.valid">
      Add
    </button>
  </form>

  <div class="todo-list">
    <div class="overlay" [ngClass]="openEditBlock ? 'active' : ''"></div>

    <div class="filter-btns">
      <button class="all-filter"
              [class.active]="currentFilter === 'all'"
              (click)="currentFilter = 'all'">
        All
      </button>
      <button class="progress-filter"
              [class.active]="currentFilter === 'progress'"
              (click)="currentFilter = 'progress'">
        In progress
      </button>
      <button class="done-filter"
              [class.active]="currentFilter === 'done'"
              (click)="currentFilter = 'done'">
        Done
      </button>
    </div>

    <ul [ngClass]="currentFilter">
      <li *ngFor="let task of tasksArray; let i = index"
          class="task clearfix"
          [class.done]="checkTaskForDone(task)"
          [class.active]="checkFilter(task)">
        <i class="material-icons task-done-icon" [ngClass]="task.done ? 'active' : ''" (click)="onDoneClick(i)">done</i>
        <p>{{task.name}}</p>
        <i class="material-icons task-close-icon" (click)="onRemoveTask(i)">close</i>
        <button class="task-edit-btn"
                [disabled]="task.done"
                (click)="currentTask = i; openEditBlock = !openEditBlock">
          Edit
        </button>
      </li>
    </ul>

    <form [formGroup]="editForm"
          class="edit"
          *ngIf="openEditBlock"
          [ngClass]="openEditBlock ? 'active' : ''">
      <h4>Edit task</h4>
      <input class="edit-input"
             type="text"
             [value]="tasksArray[currentTask].name"
             [formControl]="editForm.controls['newTaskName']" />
      <button type="submit"
              class="save-btn"
              [disabled]="!editForm.valid"
              (click)="onSaveClick($event)">
        Save
      </button>
      <i class="material-icons edit-close-icon" (click)="openEditBlock = !openEditBlock">close</i>
    </form>
  </div>
</div>

// reactjs-todo/src/app/components/Todo.js
import React from 'react';
import './Todo.scss';

export class Todo extends React.Component {
  isStorageAvailable = false;
  tasksArray         = [];
  openEditBlock      = false;
  currentTask        = 0;
  currentFilter      = 'all';

  constructor() {
    super();

    this.state = {
      taskInput: '',
      editInput: ''
    };
  }

  getTasksFromStorage() {
    if (typeof localStorage !== 'undefined') {
      this.tasksArray = JSON.parse(localStorage.getItem('tasksArray' + this.props.id)) || [];
      this.isStorageAvailable = true;
    } else {
      this.tasksArray = [];
      this.isStorageAvailable = false;
    }
  }

  saveListToStorage() {
    localStorage.setItem('tasksArray' + this.props.id, JSON.stringify(this.tasksArray));
  }

  addNewTask(event) {
    event.preventDefault();

    this.tasksArray.unshift({
      name: this.state.taskInput,
      done: false,
      id: Math.random().toString(32).substr(2, 8)
    });

    if (this.isStorageAvailable) {
      this.saveListToStorage();
    }

    this.setState({
      taskInput: ''
    });
  }

  handleTaskInputChange(event) {
    this.setState({
      taskInput: event.target.value
    });
  }

  setCurrentFilter(filter) {
    this.currentFilter = filter;
    console.log("set");
  }

  getCurrentFilter() {
    return this.currentFilter;
    console.log("heCUre");
  }

  //
  // onDoneClick(index: number) {
  //   this.tasksArray[index].done = !this.tasksArray[index].done;
  //
  //   if (this.isStorageAvailable) {
  //     this.saveListToStorage();
  //   }
  // }
  //
  // onRemoveTask(index: number) {
  //   this.tasksArray.splice(index, 1);
  //
  //   if (this.isStorageAvailable) {
  //     this.saveListToStorage();
  //   }
  // }
  //
  // onSaveClick(event) {
  //   event.preventDefault();
  //
  //   this.tasksArray[this.currentTask].name = this.editForm.controls['newTaskName'].value;
  //   this.openEditBlock = false;
  //
  //   if (this.isStorageAvailable) {
  //     this.saveListToStorage();
  //   }
  // }
  //
  // checkFilter(task) {
  //   if (task.done) {
  //     if (this.currentFilter === 'all' || this.currentFilter === 'done') {
  //       return true;
  //     } else {
  //       return false;
  //     }
  //   } else {
  //     if (this.currentFilter === 'all' || this.currentFilter === 'progress') {
  //       return true;
  //     } else {
  //       return false;
  //     }
  //   }
  // }
  //
  // checkTaskForDone(task) {
  //   return !!task.done;
  // }

  render() {
    this.getTasksFromStorage();

    return (
        <div className="todo">
          <form ref="task_form" onSubmit={this.addNewTask.bind(this)}>
            <input type="text"
                   className="task-input"
                   placeholder="Enter task name..."
                   value={this.state.taskInput}
                   onChange={this.handleTaskInputChange.bind(this)}/>
            <button type="submit" className="add-task-btn">Adds</button>
          </form>

          <div className="todo-list">
            <div className="overlay"></div>

            <div className="filter-btns">
              <button className="all-filter" onClick={this.setCurrentFilter('all')}>
                All
              </button>
              <button className="progress-filter" onClick={this.setCurrentFilter('progress')}>
                Progress
              </button>
              <button className="done-filter" onClick={this.setCurrentFilter('done')}>
                Done
              </button>
            </div>

            <ul className={this.getCurrentFilter()}>
              {this.tasksArray.map((task) => <li className="task clearfix" key={task.id}>{task.name}</li>)}
            </ul>
          </div>
        </div>
    );
  }
}

Todo.propTypes = {
  id: React.PropTypes.number
};
