// task_6-todoList_react/react_todo_list/src/todo_components/TodoItem.js
import React, {Component} from 'react'
import '../styles/TodoItem.css';
class TodoItem extends Component {
    constructor(props) {
        super(props);
        this.todo = props.todo;
        this.state = {checked: null};
        this.deleteTodo = this.deleteTodo.bind(this);
        this.switchStatusTodo = this.switchStatusTodo.bind(this);
        this.handleChange = this.handleChange.bind(this);
        this.editTodo = this.editTodo.bind(this);
    }

    deleteTodo(e) {
        this.props.removeTodo(this.todo.id);
        e.target.parentNode.remove();
    };

    switchStatusTodo(e) {
        let checkboxElement = e.target;
        if (checkboxElement.checked) {
            checkboxElement.parentNode.classList.add('completed-task');
            this.todo.checked = true;
        }
        else {
            checkboxElement.parentNode.classList.remove('completed-task');
            this.todo.checked = false;

        }
        this.props.toggleStatus(this.todo);
    };

    handleChange(event) {
        this.setState({checked: !this.state.checked});
    }
    editTodo( e) {
        var listElement = e.target.parentNode;
        var editInput = listElement.querySelector('input[type=text]');
        var label = listElement.querySelector('label');
        var temp = '';
        if (this.todo.checked !== true) {
            temp = editInput.value;
            if (listElement.classList.contains('edit-mode')) {
                if (label.innerText !== temp) {
                    if (this.validateTextInput(temp)) {
                        label.innerText = temp;
                        this.todo.text = temp;
                        this.props.editTodo(this.todo);//edit.emit(this.todo);
                    } else {
                        return;
                    }
                }
            } else {
                editInput.value = label.innerText;
            }
            this.editModeToggler(e, listElement);
        }

    }
    editModeToggler(element, elementParent) {
        elementParent.classList.toggle('edit-mode');
        element.target.classList.toggle('fa-pencil');
        element.target.classList.toggle('fa-check');
    }
    validateTextInput(inputText) {
        if (inputText === '') {
            alert('wrong');
            return false;
        }
        return true;
    }
    cancelEditing(e) {
        e.target.previousElementSibling.className = e.target.previousElementSibling.className.replace('fa-check', 'fa-pencil');
        var listElement = e.target.parentNode;
        listElement.classList.remove('edit-mode');
    }
    render() {
        return (
            <li id={this.todo.id}>
                <input type="checkbox" checked={this.state.checked} className="statusToggler"
                       onClick={this.switchStatusTodo}
                       onChange={this.handleChange}
                />
                <label >{this.todo.text}</label>
                <input type="text"/>
                <span className="edit fa fa-pencil" onClick={this.editTodo}/>
                <span className="cancel btn fa fa-undo" onClick={this.cancelEditing}/>
                <span className="delete fa fa-trash-o" onClick={this.deleteTodo}/>
            </li>
        )
    }
}
export default TodoItem;

// task_5_todoList_angular/todo-list-app/src/app/todo/todo-item/todo-item.component.ts
import {Component, Input, OnInit, Output, EventEmitter} from '@angular/core';
import {Todo} from '../models/todo';
@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.scss']
})
export class TodoItemComponent implements OnInit {
  @Input() todo: Todo;
  @Output()
  remove: EventEmitter<Todo> = new EventEmitter();
  @Output()
  toggleStatus: EventEmitter<Todo> = new EventEmitter();
  @Output()
  edit: EventEmitter<Todo> = new EventEmitter();
  @Output() openModal = new EventEmitter();

  constructor() {
  }

  switchStatusTodo(todo: Todo, e) {
    let checkboxElement = e.target;
    if (checkboxElement.checked) {
      checkboxElement.parentNode.classList.add('completed-task');
      todo.checked = true;
    }
    else {
      checkboxElement.parentNode.classList.remove('completed-task');
      todo.checked = false;

    }
    this.toggleStatus.emit(todo);
  }

  editTodo(todo: Todo, e) {
    var listElement = e.target.parentNode;
    var editInput = listElement.querySelector('input[type=text]');
    var label = listElement.querySelector('label');
    var temp = '';
    if (todo.checked !== true) {
      temp = editInput.value;
      if (listElement.classList.contains('edit-mode')) {
        if (label.innerText !== temp) {
          if (this.validateTextInput(temp)) {
            label.innerText = temp;
            todo.text = temp;
            this.edit.emit(todo);
          } else {
            return;
          }
        }
      } else {
        editInput.value = label.innerText;
      }
      this.editModeToggler(e, listElement);
    }
  }

  editModeToggler(element, elementParent) {
    elementParent.classList.toggle('edit-mode');
    element.target.classList.toggle('fa-pencil');
    element.target.classList.toggle('fa-check');
  }

  validateTextInput(inputText) {
    if (inputText === '') {
      this.openModal.emit();
      return false;
    }
    return true;
  }

  removeTodo(todo: Todo, e) {
    var listElement = e.target.parentNode;
    listElement.remove();
    this.remove.emit(todo);
  }

  cancelEditing(e) {
    var listElement = e.target.parentNode;
    listElement.classList.remove('edit-mode');
  }

  ngOnInit() {

  }
}

<li [id]="todo.id" [class.completed-task]="todo.checked">
  <input type="checkbox" class="statusToggler" [checked]="todo.checked" (click)="switchStatusTodo(todo,$event)" >
  <label >{{todo.text}}</label>
  <input type="text">
  <span class="edit fa fa-pencil" (click)="editTodo(todo,$event)"></span>
  <span class="cancel btn fa fa-undo" (click)="cancelEditing($event)"></span>
  <span class="delete fa fa-trash-o" (click)="removeTodo(todo,$event)"></span>
</li>
