// task_6-todoList_react/react_todo_list/src/todo_components/App.js
import React, {Component} from 'react';
import '../styles/App.css';
import NewTodoInput from "./NewTodoInput";
import TodoFilters from "./TodoFilters";
import TodoList from "./TodoList";

import LocalStorageService from "./LocalStorageService"
class App extends Component {


    constructor(props) {
        super(props);
        this.localStorageService = new LocalStorageService();
        this.state = {
            todosArray: []
        };
        this.getTodos = this.getTodos.bind(this);
        this.addNewTodo = this.addNewTodo.bind(this);
        this.deleteTodo = this.deleteTodo.bind(this);
        this.editTodoText = this.editTodoText.bind(this);
        this.onSwitchStatusTodo=this.onSwitchStatusTodo.bind(this);
    }

    getTodos() {
        return this.localStorageService.getTodos();
    }

    addNewTodo(newTodo) {
        this.localStorageService.addTodo(newTodo);
        this.state.todosArray.push(newTodo);
        this.setState({todosArray:this.state.todosArray});

    }
    deleteTodo(id) {
        console.log(this.localStorageService);
        this.localStorageService.deleteTodo(id);

       // console.log(id);
    }
    onSwitchStatusTodo(todo) {

        this.localStorageService.editStatusOfTodo(todo.id, todo.checked);

    }
    componentDidMount() {
        this.localStorageService.isLocalStorageAvailable();
        this.setState({todosArray: this.localStorageService.getTodos()})
    }
    editTodoText(todo){
        this.localStorageService.editTextTodo(todo.text, todo.id);
    }


    render() {
        const todos=this.state.todosArray;
        return (
            <div className="todo-plugin">
                <div className="todo-manager">
                    <NewTodoInput onAddNewTodo={this.addNewTodo}/>
                    <TodoFilters />
                </div>
                <TodoList
                    todosArray={todos}
                    toggleStatus={this.onSwitchStatusTodo}
                    removeTodo={this.deleteTodo}
                    editTodo={this.editTodoText}
                    />

            </div>
        );
    }
}

export default App;

// task_5_todoList_angular/todo-list-app/src/app/app.component.ts
import {Component, OnInit} from '@angular/core';
import {Todo} from "./todo";
import {LocalStorageService} from "./local-storage.service";
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: []
})
export class AppComponent implements OnInit {
  todos: Todo[];

  constructor(private localStorageService: LocalStorageService) {
   // this.todos=this.getTodos();
    // console.log( this.getTodos());
  }

  getTodos() {
    return this.localStorageService.getTodos();
  }

  onAddTodo(todo: Todo) {
    this.localStorageService.addTodo(todo);
    this.todos=this.getTodos();
  }

  onSwitchStatusTodo(todo: Todo) {
    console.log(todo.checked);
    this.localStorageService.editStatusTodo(todo.id, todo.checked);
  }

  // rename from removeTodo
  onRemoveTodo(todo: Todo) {
    this.localStorageService.removeTodo(todo.id);
  }
  onEditTodo(todo:Todo){
  //  console.log(todo.text);
  //  this.edit.emit(todo);
    this.localStorageService.editTextTodo(todo.text,todo.id);
  }
  ngOnInit() {
    this.todos = this.getTodos();
  }

}

<div class="wrapper">
  <div class="todo-plugin">
    <!--manager components-->
    <div class="todo-manager">
      <app-new-todo-input (add)="onAddTodo($event)"></app-new-todo-input>
      <app-todo-filters></app-todo-filters>
    </div>
    <!--allTodosList components-->
    <app-todo-list *ngIf="todos"
                   [todos]="todos"
                   (toggleStatus)="onSwitchStatusTodo($event)"
                   (remove)="onRemoveTodo($event)"
                   (edit)="onEditTodo($event)">
    </app-todo-list >
  </div>
</div>
