// reactjs-todo/src/app/components/AddForm/AddForm.js
import React from 'react';
import './AddForm.css';

export const AddForm = (props) => {
  props = props.data;

  let inputName = '';

  let addNewTask  = function(event) {
    event.preventDefault();

    if (!inputName.value.length) {
      return;
    }

    const tempTasksArray = props.data.tasksArray;
    tempTasksArray.unshift({
      name: inputName.value,
      done: false,
      id: Math.random().toString(32).substr(2, 8)
    });

    inputName.value = '';

    props.setTasksArray(tempTasksArray);

    console.log(props.data);
    if (props.data.isStorageAvailable) {
      console.log(props.data.tasksArray);
      localStorage.setItem(props.data.storageName, JSON.stringify(props.data.tasksArray));
    }
  };

  return (
    <form onSubmit={addNewTask}>
      <input type="text"
             className="task-input"
             placeholder="Enter task name..."
             ref={(name) => inputName = name}/>
      <button type="submit" className="add-task-btn">
        Add
      </button>
    </form>
  );
};

// angular-todo/angular2-todo-app/src/app/todo/add-form/add-form.component.ts
import { Component                          } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

import { DataService                        } from '../core/data.service';
import { StorageService                     } from '../shared/storage.service';

@Component({
  selector: 'app-add-form',
  templateUrl: './add-form.component.html',
  styleUrls: ['./add-form.component.css']
})

export class AddFormComponent {
  addForm: FormGroup;

  constructor(private _formBuilder: FormBuilder,
              private _dataService: DataService,
              private _storageService: StorageService) {
    this.addForm = this._formBuilder.group({
      'taskName': [null, Validators.required]
    });
  }

  addNewTask(form) {
    const tempTasksArray = this._dataService.tasksArray;
    tempTasksArray.unshift({
      name: form.taskName,
      done: false
    });

    this._dataService.tasksArray = tempTasksArray;

    if (this._dataService.isStorageAvailable) {
      this._storageService.saveData(this._dataService.storageName, this._dataService.tasksArray);
    }

    this.addForm.reset();
  }
}

<form [formGroup]="addForm" (ngSubmit)="addNewTask(addForm.value)">
  <input class="task-input"
         type="text"
         placeholder="Enter task name..."
         [formControl]="addForm.controls['taskName']" />
  <button type="submit"
          class="add-task-btn"
          [disabled]="!addForm.valid">
    Add
  </button>
</form>
