// angular-todo/angular2-todo-app/src/app/todo/task-list/task-list.component.ts
import { Component   } from '@angular/core';

import { DataService } from '../core/data.service';

@Component({
  selector: 'app-task-list',
  templateUrl: './task-list.component.html',
  styleUrls: ['./task-list.component.css']
})

export class TaskListComponent {
  constructor(public _dataService: DataService) { }
}

<div class="todo-list">
  <div class="overlay" [class.active]="_dataService.openEditBlock"></div>

  <div class="filter-btns">
    <button class="all-filter"
            [class.active]="_dataService.currentFilter === 'all'"
            (click)="_dataService.currentFilter = 'all'">
      All
    </button>
    <button class="progress-filter"
            [class.active]="_dataService.currentFilter === 'progress'"
            (click)="_dataService.currentFilter = 'progress'">
      In progress
    </button>
    <button class="done-filter"
            [class.active]="_dataService.currentFilter === 'done '"
            (click)="_dataService.currentFilter = 'done'">
      Done
    </button>
  </div>

  <ul [ngClass]="_dataService.currentFilter">
    <app-task *ngFor="let task of _dataService.tasksArray; let i = index"
              [index]="i">
    </app-task>
  </ul>
</div>

// reactjs-todo/src/app/containers/Todo/TaskList.js
import React from 'react';
import { Task } from './Task';
import './TaskList.scss';

export const TaskList = (props) => {
  return (
    <div className='todo-list'>
      <div className={'overlay ' + (props.openEditBlock ? 'active' : '')}></div>

      <div className="filter-btns">
        <button className={'all-filter ' + (props.currentFilter === 'all' ? 'active' : '')}
                onClick={props.filterActions.setFilterToAll}>
          All
        </button>
        <button className={'progress-filter ' + (props.currentFilter === 'progress' ? 'active' : '')}
                onClick={props.filterActions.setFilterToProgress}>
          Progress
        </button>
        <button className={'done-filter ' + (props.currentFilter === 'done' ? 'active' : '')}
                onClick={props.filterActions.setFilterToDone}>
          Done
        </button>
      </div>

      <ul className={props.currentFilter}>
        {props.tasksArray.map((task, index) => {
          return (
              <Task
                  key={task.id}
                  actions={props.taskActions}
                  task={task}
                  index={index}
              />
          );
        })}
      </ul>
    </div>
  );
};
