// angular-todo/angular2-todo-app/src/app/todo/task-list/task/task.component.ts
import { Component, Input  } from '@angular/core';

import { StorageService    } from '../../shared/storage.service';
import { DataService       } from '../../core/data.service';

@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.css']
})

export class TaskComponent {
  @Input()
  index: number;

  constructor(private _storageService: StorageService,
              public _dataService: DataService) { }

  onEditClick() {
    this._dataService.currentTask = this.index;
    this._dataService.openEditBlock = !this._dataService.openEditBlock;
  }

  onDoneClick() {
    this._dataService.tasksArray[this.index].done = !this._dataService.tasksArray[this.index].done;

    if (this._dataService.isStorageAvailable) {
      this._storageService.saveData(this._dataService.storageName, this._dataService.tasksArray);
    }
  }

  onRemoveTask() {
    this._dataService.tasksArray.splice(this.index, 1);

    if (this._dataService.isStorageAvailable) {
      this._storageService.saveData(this._dataService.storageName, this._dataService.tasksArray);
    }
  }

  checkFilter() {
    if (this._dataService.tasksArray[this.index].done) {
      return (this._dataService.currentFilter === 'all' || this._dataService.currentFilter === 'done');
    } else {
      return (this._dataService.currentFilter === 'all' || this._dataService.currentFilter === 'progress');
    }
  }

  checkTaskForDone() {
    return !!this._dataService.tasksArray[this.index].done;
  }
}

<li class="task clearfix"
    [class.done]="checkTaskForDone()"
    [class.active]="checkFilter()">
  <i class="material-icons task-done-icon"
     [class.active]="_dataService.tasksArray[index].done"
     (click)="onDoneClick()">
    done
  </i>
  <p>{{_dataService.tasksArray[index].name}}</p>
  <i class="material-icons task-close-icon" (click)="onRemoveTask()">close</i>
  <button class="task-edit-btn"
          [disabled]="_dataService.tasksArray[index].done"
          (click)="onEditClick()">
    Edit
  </button>
</li>

// reactjs-todo/src/app/containers/Todo/Task.js
import React from 'react';
import './Task.scss';

export const Task = (props) => {
  return (
    <li className={'task clearfix ' + ((props.task.done) ? 'done' : '')}>
      <i className={'material-icons task-done-icon ' + ((props.task.done) ? 'active' : '')}
         onClick={(() => {props.actions.onDoneClick(props.index)})}>
        done
      </i>
      <p>{props.task.name}</p>
      <i className='material-icons task-close-icon' onClick={(() => {props.actions.onRemoveTask(props.index)})}>
        close
      </i>
      <button className='task-edit-btn'
              disabled={props.task.done}
              onClick={(() => {props.actions.handleEditClick(props.index)})}>
        Edit
      </button>
    </li>
  );
};
